### ISSUE TITLE
Lyrics search

### ISSUE THREAD

**Issue by qcerasmus** [Chowbi/DeeToolBar#1]
Hi, 

I really love this extension and thought it would be cool to have functionality to open a new tab to display lyrics. Please let me know what you think?

I have started with the dev to do it, and you should be able to see it in my fork. I'm having trouble testing it though.

Thanks!

**Comment by Chowbi** [comment]
Hello,

I looked for your pull request but reverted it :
    - The choice of the lyric website seems arbitrary.
    - All requests I tested responded 404
    - Deezer include a lyric functionnality

One more confident way would use an api or a search url to find lyrics.

To me it seems useless to add a toolbar button to click on the deezer lyric button.

Regards.

Chowbi
