### ISSUE TITLE
Artist and Track in the popup does not show any separation

### ISSUE THREAD

**Issue by ostracize** [Chowbi/DeeToolBar#13]
### Current behaviour
When playing, the toolbar shows:

- TrackArtist

### Expected behaviour
When playing, the toolbar shows:

- Track - Artist

**Comment by Chowbi** [comment]
Resolved by 331f0e4103dac7b355e97955dd18b30209f24568

**Comment by Chowbi** [comment]
The new version has been submitted to mozilla
